"""add is_verified and is_active and last_login

Revision ID: 460ec06adf17
Revises: 01027b45ae47
Create Date: 2026-01-06 16:14:49.560286

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '460ec06adf17'
down_revision: Union[str, Sequence[str], None] = '01027b45ae47'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_verified', sa.Boolean(), nullable=True), schema='core')
    op.add_column('users', sa.Column('is_active', sa.Boolean(), nullable=True), schema='core')
    op.add_column('users', sa.Column('last_login', sa.DateTime(timezone=True), nullable=True), schema='core')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'last_login', schema='core')
    op.drop_column('users', 'is_active', schema='core')
    op.drop_column('users', 'is_verified', schema='core')
    # ### end Alembic commands ###
