#!/bin/bash
set -e


psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
    
    DO \$\$
    BEGIN
        IF NOT EXISTS (SELECT FROM pg_catalog.pg_roles WHERE rolname = '$POSTGRES_CORE_DB_USER') THEN
            CREATE USER $POSTGRES_CORE_DB_USER WITH PASSWORD '$POSTGRES_CORE_DB_PASS';
        END IF;
    END
    \$\$;

    DO \$\$
    BEGIN
        IF NOT EXISTS (SELECT FROM pg_catalog.pg_roles WHERE rolname = '$POSTGRES_AI_DB_USER') THEN
            CREATE USER $POSTGRES_AI_DB_USER WITH PASSWORD '$POSTGRES_AI_DB_PASS';
        END IF;
    END
    \$\$;

    DO \$\$
    BEGIN
        IF NOT EXISTS (SELECT FROM pg_catalog.pg_roles WHERE rolname = '$POSTGRES_NOTIFICATION_DB_USER') THEN
            CREATE USER $POSTGRES_NOTIFICATION_DB_USER WITH PASSWORD '$POSTGRES_NOTIFICATION_DB_PASS';
        END IF;
    END
    \$\$;

    CREATE SCHEMA IF NOT EXISTS core AUTHORIZATION $POSTGRES_CORE_DB_USER;
    CREATE SCHEMA IF NOT EXISTS ai AUTHORIZATION $POSTGRES_AI_DB_USER;
    CREATE SCHEMA IF NOT EXISTS notification AUTHORIZATION $POSTGRES_NOTIFICATION_DB_USER;

    GRANT ALL PRIVILEGES ON SCHEMA core TO $POSTGRES_CORE_DB_USER;
    GRANT ALL PRIVILEGES ON SCHEMA ai TO $POSTGRES_AI_DB_USER;
    GRANT ALL PRIVILEGES ON SCHEMA notification TO $POSTGRES_NOTIFICATION_DB_USER;

EOSQL